version: '3.5'
services:
  cloud-media-scripts:
    build: .
    container_name: cloud-media-scripts
    restart: unless-stopped
    cap_add:
      - ALL
      - MKNOD
      - SYS_ADMIN
    environment:
      TZ: Asia/Hong_Kong
      PUID: 1001
      PGID: 996
      ENCRYPT_MEDIA: 1
      BUFFER_SIZE: 500m
      MAX_READ_AHEAD: 30G
      CHECKERS: 16
      RCLONE_CLOUD_ENDPOINT: "gd-crypt:"
      RCLONE_LOCAL_ENDPOINT: "local-crypt:"
      CHUNK_SIZE: 10M
      CLEAR_CHUNK_MAX_SIZE: 1000G
      CLEAR_CHUNK_AGE: 24h
      DATE_FORMAT: "+%F@%T"
      REMOVE_LOCAL_FILES_BASED_ON: space
      REMOVE_LOCAL_FILES_WHEN_SPACE_EXCEEDS_GB: 2000
      FREEUP_ATLEAST_GB: 1000
      REMOVE_LOCAL_FILES_AFTER_DAYS: 10
      READ_ONLY: 1
      PLEX_URL: ""
      PLEX_TOKEN: ""
    volumes:
      - /srv/dev-disk-by-label-Data/media/local-media:/local-media:shared
      - /srv/dev-disk-by-label-Data/media/local-decrypt:/local-decrypt:shared
      - /srv/dev-disk-by-label-Data/media/chunks:/chunks
      - /srv/dev-disk-by-label-Docker/cloud-media-scripts/db:/data/db
      - /srv/dev-disk-by-label-Docker/cloud-media-scripts/config:/config
      - /srv/dev-disk-by-label-Docker/cloud-media-scripts/logs:/log
    privileged: true
    devices:
      - /dev/fuse
